services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    container_name: scraper-backend
    environment:
      - SERVER_PORT=8000
      - MONGODB_URI=mongodb://mongo:27017/scraped
      - MONGODB_DB=scraped
      - TARGET_URL=https://example.com
      - MAX_CONCURRENCY=4
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    depends_on:
      - mongo
    security_opt:
      - seccomp:unconfined
      - no-new-privileges:false
    shm_size: 1gb
    ports:
      - "8000:8000"
volumes:
  mongo-data:
    name: scraper_mongo_data
